In [26]:
def describe(x):
    print("Type: ",x.type())
    print("Shape/size:",x.shape)
    print("Values: \n{}".format(x))


In [27]:
import torch
describe(torch.Tensor(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5730, 1.2311, 1.4583],
        [0.5106, 1.1654, 0.0743]])


In [28]:
describe(torch.Tensor(5,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[-4.1342e-28,  1.1855e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [29]:
describe(torch.rand(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.3032, 0.5932, 0.0966],
        [0.5131, 0.5479, 0.0600]])


In [30]:
describe(torch.randn(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.3656, -0.3477,  1.1114],
        [-0.5743,  1.1999,  0.9785]])


In [31]:
describe(torch.zeros(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
x=torch.ones(2,3)
describe(x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [33]:
x.fill_(5) # We can also create tensors all filled with the same scalar. For creating a tensor of zeros or ones, we have built-in functions, and for filling it with specific values, we can use the fill_() method. Any PyTorch method with an underscore (_) refers to an in-place operation; that is, it modifies the content in place without creating a new object
describe(x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [34]:
x=torch.tensor([[1,2,3],
               [4,5,6]])
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [35]:
import numpy as np

In [37]:
arr=np.random.standard_normal((2,3))
describe(torch.from_numpy(arr))

Type:  torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.2028,  0.6019, -0.6125],
        [-2.7857,  1.6913, -0.5847]], dtype=torch.float64)


In [39]:
x=torch.FloatTensor([[1,2,3],
                     [4,5,6]])
describe(x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [41]:
x=x.long()
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [45]:
x=torch.tensor([[1,2,3],
                [4,5,6]],dtype=torch.int64)
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [46]:
x.size()

torch.Size([2, 3])

### Tensor Operations

In [47]:
x=torch.randn(2,3)
describe(x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.6702, -1.1409, -1.6980],
        [-0.6863, -1.8059, -0.8677]])


In [48]:
describe(torch.add(x,x))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 3.3404, -2.2818, -3.3960],
        [-1.3727, -3.6119, -1.7355]])


In [50]:
describe(x+x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 3.3404, -2.2818, -3.3960],
        [-1.3727, -3.6119, -1.7355]])


In [51]:
x=torch.arange(6)
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([6])
Values: 
tensor([0, 1, 2, 3, 4, 5])


In [52]:
x=x.view(2,3)
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [54]:
describe(torch.sum(x,dim=0))

Type:  torch.LongTensor
Shape/size: torch.Size([3])
Values: 
tensor([3, 5, 7])


In [55]:
describe(torch.sum(x,dim=1))

Type:  torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([ 3, 12])


In [56]:
describe(torch.transpose(x,0,1))

Type:  torch.LongTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


### Indexing, Slicing, and Joining

In [57]:
x=torch.arange(6).view(2,3)
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [59]:
describe(x[:1,:2])

Type:  torch.LongTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[0, 1]])


In [61]:
describe(x[:2,:2])

Type:  torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 1],
        [3, 4]])


In [62]:
describe(x[0,1])

Type:  torch.LongTensor
Shape/size: torch.Size([])
Values: 
1


In [65]:
indices=torch.LongTensor([0,2])
describe(torch.index_select(x,dim=1,index=indices))

Type:  torch.LongTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[0, 2],
        [3, 5]])


tensor([0, 2])

In [67]:
row_indices=torch.arange(2).long()
col_indices=torch.LongTensor([0,1])
describe(x[row_indices,col_indices])

Type:  torch.LongTensor
Shape/size: torch.Size([2])
Values: 
tensor([0, 4])


In [68]:
x=torch.arange(6).view(2,3)
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [69]:
describe(torch.cat([x,x],dim=0))

Type:  torch.LongTensor
Shape/size: torch.Size([4, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])


In [70]:
describe(torch.cat([x,x],dim=1))

Type:  torch.LongTensor
Shape/size: torch.Size([2, 6])
Values: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])


In [71]:
describe(torch.stack([x,x]))

Type:  torch.LongTensor
Shape/size: torch.Size([2, 2, 3])
Values: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [76]:
x1=torch.arange(6).view(2,3).float()
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [77]:
x2=torch.ones(3,2)
x2[:,1]+=1
describe(x2)

Type:  torch.FloatTensor
Shape/size: torch.Size([3, 2])
Values: 
tensor([[1., 2.],
        [1., 2.],
        [1., 2.]])


In [78]:
describe(torch.mm(x1,x2))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[ 3.,  6.],
        [12., 24.]])


In [85]:
x=torch.ones(2,2,requires_grad=True)
describe(x)
print(x.grad is None)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [89]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 2])
Values: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [92]:
z=y.mean()
describe(z)
z.backward()
print(x.grad is None)

Type:  torch.FloatTensor
Shape/size: torch.Size([])
Values: 
21.0
False


In [102]:
x=torch.randn(1,2,requires_grad=True)
describe(x)
y=(x**2)+2
z=y.sum()

describe(y)
z.backward()


Type:  torch.FloatTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[ 1.3828, -0.3535]], requires_grad=True)
Type:  torch.FloatTensor
Shape/size: torch.Size([1, 2])
Values: 
tensor([[3.9123, 2.1249]], grad_fn=<AddBackward0>)


In [103]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print (device)

cpu
