In [26]:
def describe(x):
    print("Type: ",x.type())
    print("Shape/size:",x.shape)
    print("Values: \n{}".format(x))


In [27]:
import torch
describe(torch.Tensor(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.5730, 1.2311, 1.4583],
        [0.5106, 1.1654, 0.0743]])


In [28]:
describe(torch.Tensor(5,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([5, 3])
Values: 
tensor([[-4.1342e-28,  1.1855e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [29]:
describe(torch.rand(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0.3032, 0.5932, 0.0966],
        [0.5131, 0.5479, 0.0600]])


In [30]:
describe(torch.randn(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.3656, -0.3477,  1.1114],
        [-0.5743,  1.1999,  0.9785]])


In [31]:
describe(torch.zeros(2,3))

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [32]:
x=torch.ones(2,3)
describe(x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [33]:
x.fill_(5) # We can also create tensors all filled with the same scalar. For creating a tensor of zeros or ones, we have built-in functions, and for filling it with specific values, we can use the fill_() method. Any PyTorch method with an underscore (_) refers to an in-place operation; that is, it modifies the content in place without creating a new object
describe(x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [34]:
x=torch.tensor([[1,2,3],
               [4,5,6]])
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [35]:
import numpy as np

In [37]:
arr=np.random.standard_normal((2,3))
describe(torch.from_numpy(arr))

Type:  torch.DoubleTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[ 1.2028,  0.6019, -0.6125],
        [-2.7857,  1.6913, -0.5847]], dtype=torch.float64)


In [39]:
x=torch.FloatTensor([[1,2,3],
                     [4,5,6]])
describe(x)

Type:  torch.FloatTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [41]:
x=x.long()
describe(x)

Type:  torch.LongTensor
Shape/size: torch.Size([2, 3])
Values: 
tensor([[1, 2, 3],
        [4, 5, 6]])
